trigger:
- main

pool:
  name: Default

steps:
- script: |
    flutter pub global activate junitreport
    mkdir -p test-results
    flutter test --machine | tojunit --output test-results/output.xml
  displayName: 'Test'
- script: flutter build web --base-href "/minigames/"
  displayName: 'Build'
- script: |
    cp -r assets/* build/web/assets
    zip -r flutter.zip build/web
  displayName: 'Zip artifact'